Repository elephantatech/BookLibrary, pull requests merged in 2022-02, with the labels that each got.

#4 Backend Data Design
  Backend-Design.md
  README.md
Labels: documentation

#10 dev envirornment setup for project
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#14 fixed link for backend design and format for the list
  README.md
Labels: bug, documentation

#15 Issue#13 - Updated folder structure and added basic code
  .gitignore
  fastapi-backend/__init__.py
  fastapi-backend/config.py
  fastapi-backend/entrypoint.sh
  fastapi-backend/main/__init__.py
  fastapi-backend/main/app.py
  fastapi-backend/poetry.lock
  fastapi-backend/pyproject.toml
  fastapi-backend/requirements.txt
Labels: enhancement

#18 Issue#3 Book Model
  .gitignore
  README.md
  Testing.md
  fastapi-backend/config.py
  fastapi-backend/models/__init__.py
  fastapi-backend/models/books.py
  fastapi-backend/poetry.lock
  fastapi-backend/pyproject.toml
  fastapi-backend/tests/__init__.py
  fastapi-backend/tests/book_test.py
Labels: enhancement
